### ISSUE TITLE
module 'optimizer' has no attribute 'load_state_dict'

### ISSUE THREAD

**Issue by Ximoi** [NVIDIA/semantic-segmentation#14] opened 2019-08-08 10:14 UTC
Thank you for providing code! There is something wrong when I resume the checkpoint.

Traceback (most recent call last):
  File "train.py", line 326, in <module>
    main()
  File "train.py", line 169, in main
    args.snapshot, args.restore_optimizer)
  File "/home/fuyi02/vos/semantic-segmentation/optimizer.py", line 61, in load_weights
    net, optimizer = restore_snapshot(net, optimizer, snapshot_file, restore_optimizer_bool)
  File "/home/fuyi02/vos/semantic-segmentation/optimizer.py", line 77, in restore_snapshot
    optimizer.load_state_dict(checkpoint['optimizer'])
AttributeError: module 'optimizer' has no attribute 'load_state_dict'

It seems that the definition of optimizer do not have 'load_state_dict'。。

**Comment by bryanyzhu** [comment] 2019-08-08 17:19
Hi, thank you for catching this, it is a typo bug. Please change this [line](https://github.com/NVIDIA/semantic-segmentation/blob/333ffbcdfbf3247fc20e5a656e80b382d2904668/train.py#L168) from 
```
optimizer.load_weights(net, optimizer, args.snapshot, args.restore_optimizer)
```

to 
```
optimizer.load_weights(net, optim, args.snapshot, args.restore_optimizer)
```

The error is because the naming is confused. We should pass in the real optimizer, but instead we actually passed in the file `optimizer.py`. So the file `optimizer.py` of course has no attribute 'load_state_dict'.

I will update the repo now as well. Thank you.

**Comment by bryanyzhu** [comment] 2019-08-09 23:31
@Ximoi Just a follow up check, does this fix work on you end?

**Comment by Ximoi** [comment] 2019-08-10 06:23
Sorry, the fix did not work and the bug still exists as follow:
Traceback (most recent call last):
  File "train.py", line 326, in <module>
    main()
  File "train.py", line 169, in main
    args.snapshot, args.restore_optimizer)
  File "/home/fuyi02/vos/semantic-segmentation/optimizer.py", line 61, in load_weights
    net, optimizer = restore_snapshot(net, optim, snapshot_file, restore_optimizer_bool)
  File "/home/fuyi02/vos/semantic-segmentation/optimizer.py", line 77, in restore_snapshot
    optimizer.load_state_dict(checkpoint['optimizer'])
AttributeError: module 'torch.optim' has no attribute 'load_state_dict'

**Comment by Ximoi** [comment] 2019-08-10 06:32
@bryanyzhu  Thank you for your help and it works!

**Comment by bryanyzhu** [comment] 2019-08-10 06:34
@Ximoi Glad to know it works. Will close the issue for now. Thank you for catching it.

**Comment by Ximoi** [comment] 2019-08-10 12:39
Hi, I find another small bug in inference when loading checkpoint
The parameter layer in the training checkpoint module starts with 'module' like 'module.mod1.conv1.weight', but the network in the 'eval_cityscapes_WideResNet38.sh' seems that it starts with 'module.module. ....'  

=====================Could not load imagenet weights=======================
 Model params = 137.1M
 Checkpoint Load Compelete
 Skipped loading parameter module.mod1.conv1.weight
 Skipped loading parameter module.mod2.block1.bn1.0.weight
 Skipped loading parameter module.mod2.block1.bn1.0.bias
 Skipped loading parameter module.mod2.block1.bn1.0.running_mean
.........

**Comment by bryanyzhu** [comment] 2019-08-10 16:03
I don't know if you change anything in the code, but I couldn't reproduce your output on my end. I can run the code smoothly, my output is like this: 

```
Running inference on ../../pretrained_models/cityscapes_best.pth
Saving Results : ./logs/
Using regular batch norm
Logging : ./logs/../val/eval_2019_08_10_15_58_21_rank_0.log
08-10 15:58:21.200 Network Arch: network.deepv3.DeepWV3Plus
08-10 15:58:21.200 CV split: 0
08-10 15:58:21.200 Exp_name: ..
08-10 15:58:21.200 Ckpt path: ./logs/
08-10 15:58:21.201 Scales : 1.0
08-10 15:58:21.201 Inference mode: sliding
08-10 15:58:21.201 val fine cities: ['val/lindau', 'val/frankfurt', 'val/munster']
08-10 15:58:21.203 Cityscapes-val: 500 images
08-10 15:58:21.204 Load model file: ../../pretrained_models/cityscapes_best.pth
08-10 15:58:21.222 Trunk: WideResnet38
08-10 15:58:22.346 Global Average Pooling Initialized
=====================Could not load imagenet weights=======================
08-10 15:58:23.239 Model params = 137.1M
08-10 15:58:32.660 Checkpoint Load Compelete
eval val:   0%|                                                                                                                                                                   | 0/500 [00:00<?, ?it/s]/home/ubuntu/yizhu/code/second/semantic-segmentation/utils/misc.py:68: RuntimeWarning: invalid value encountered in true_divide
  return np.diag(hist) / (hist.sum(1) + hist.sum(0) - np.diag(hist))
Mean IOU: 75.73:   1%|█▍                                                     
```

Just want to confirm, you use the `cityscapes_best.pth` model, right?

**Comment by Ximoi** [comment] 2019-08-12 01:39
Sorry, I just made a mistake.

**Comment by Ximoi** [comment] 2019-08-12 01:40
Sorry, the eval.py works and I just made a mistake.

**Comment by bryanyzhu** [comment] 2019-08-12 05:21
No problem, glad it works 😄

**Comment by karansapra** [comment] 2019-08-15 21:42
Can we close the issue ? @Ximoi  @bryanyzhu

**Comment by Ximoi** [comment] 2019-08-16 06:16
yes @karansapra

**Comment by karansapra** [comment] 2019-08-16 15:44
Thank guys!

**Closed by karansapra** 2019-08-16 15:44 UTC
